unionai/helm-charts

charts/dataplane/values.yaml

ctx/chore(dataplane): set default resource values for services

---

charts/dataplane/Chart.yaml

ctx/rel(dataplane): version 2025.2.2

---

charts/dataplane/Chart.yaml

ctx/chore(dataplane): publish 2025.2.6

---

charts/dataplane/templates/_helpers.tpl

ctx/fix(dataplane): address additionalPodEnvVars templating errors

---

charts/dataplane/Chart.yaml
charts/dataplane/templates/operator/deployment.yaml
charts/dataplane/values.yaml

ctx/feat(dataplane): embbed cloudflared tunnel service

---

README.md

ctx/chore(docs): update installation instructions

---

.gitignore
providers/aws/eks.tf
providers/aws/eks_auth.tf
providers/aws/iam.tf
providers/aws/locals.tf
providers/aws/provider.tf
providers/aws/storage.tf
providers/aws/terraform.tfvars
providers/aws/variables.tf
providers/aws/vpc.tf

ctx/feat(providers): add aws terraform minimal examples

---

charts/dataplane/Chart.yaml
charts/dataplane/templates/_helpers.tpl
charts/dataplane/templates/datacatalog/configmap.yaml
charts/dataplane/templates/datacatalog/deployment.yaml
charts/dataplane/templates/datacatalog/service.yaml
charts/dataplane/templates/datacatalog/serviceaccount.yaml
charts/dataplane/values.yaml
charts/sandbox/Chart.yaml
charts/sandbox/templates/_helpers.tpl
charts/sandbox/templates/postgres/deployment.yaml
charts/sandbox/templates/postgres/service.yaml
charts/sandbox/values.yaml

ctx/feat(dataplane): add datacatalog service

---

charts/dataplane/Chart.yaml
charts/dataplane/templates/operator/configmap.yaml
charts/dataplane/templates/operator/deployment-proxy.yaml
charts/dataplane/templates/operator/deployment.yaml
charts/dataplane/values.yaml

ctx/chore(dataplane): pull in tunnel to proxy move

---

charts/dataplane/values.yaml

set route prefix to /prometheus

set route prefix to /prometheus

---

charts/dataplane/templates/_storage.tpl

ctx/feat(dataplane): add aws storage provider

---

providers/aws/eks.tf

Whoops, accidentally commented this out in a prior PR.

fix(terraform-aws): uncomment autoscaler deployment

---

charts/dataplane/values.yaml

add debugger link

---

charts/dataplane/Chart.yaml

release/dataplane: 2025.3.3

---

charts/dataplane/Chart.yaml

release/dataplane: 2025.3.4

---

providers/oci/cluster.tf
providers/oci/variables.tf

ctx/chore(oci): add lookup for image name

---

.github/workflows/checks.yaml
Makefile

ctx/chore(ci): lint checks

---

charts/dataplane/templates/_storage.tpl
tests/generated/dataplane.oci.yaml

ctx/fix(dataplane): remove duplicate config entry

---

charts/dataplane/templates/operator/serviceaccount-proxy-secret.yaml
tests/generated/dataplane.oci.yaml

proxy secret role patch

---

charts/dataplane-crds/Chart.yaml

ctx/release: dataplane-crds v2025.3.0

---

charts/dataplane/Chart.yaml
charts/knative-operator/Chart.yaml
charts/knative-operator/templates/knative-operator.yaml

ctx/chore: add knative deps to dataplane

---

charts/knative-operator/Chart.yaml
charts/knative-operator/templates/_helpers.tpl

Fixes a syntax error in the helpers for `knative-operator` chart

fix(knative-operator): fix syntax error

---

README.md

ctx/chore(docs): update install instructions

---

charts/dataplane/values.yaml

ctx/chore(dataplane): add value comments

---

charts/dataplane-crds/Chart.yaml
charts/dataplane/Chart.yaml

ctx/release(union): 2025.4.0

---

charts/dataplane/templates/_helpers.tpl
tests/generated/dataplane.aws.yaml
tests/generated/dataplane.oci.yaml

Add check for fluenbit config map to avoid creating unnecessary fluentbit output plugin

Add check for fluenbit config map

---

charts/dataplane/Chart.yaml
charts/dataplane/templates/_helpers.tpl
tests/generated/dataplane.aws.yaml
tests/generated/dataplane.dcgm-exporter.yaml
tests/generated/dataplane.nodeobserver.yaml
tests/generated/dataplane.oci.yaml

Was innappropriately creating buildkit resources when it shouldn't

Fix `imagebuilder.buildkit.enabled` check

---

charts/dataplane-crds/README.md
charts/dataplane/README.md
charts/knative-operator/README.md
charts/sandbox/README.md

Regenerated chart docs for new versions

ctx/chore(docs): regenerate helm docs

---

charts/dataplane/templates/clusterresourcesync/deployment.yaml
charts/dataplane/templates/common/auth-secret.yaml
charts/dataplane/templates/operator/deployment-proxy.yaml
charts/dataplane/templates/operator/deployment.yaml
charts/dataplane/templates/propeller/deployment.yaml
charts/dataplane/values.yaml

Secret enable field

---

charts/controlplane/templates/common/_ingress-unprotected.yaml
charts/controlplane/values.yaml
tests/generated/controlplane.aws.billing-enable.yaml
tests/generated/controlplane.aws.yaml

Verified this on new canary cluster

Update the ingress to have healthchecks for admin and updates to values file

---

charts/controlplane/Chart.yaml
charts/dataplane-crds/Chart.yaml
charts/dataplane/Chart.yaml
charts/knative-operator/Chart.yaml
charts/sandbox/Chart.yaml
tests/generated/controlplane.aws.billing-enable.yaml
tests/generated/controlplane.aws.yaml

Release contains 
* fixes to include migrate scripts in the default values file
* fixes to include grpc health apis in grpc ingress object

Release version 2025.6.3

---

charts/controlplane/templates/common/_ingress-protected.yaml
tests/generated/controlplane.aws.billing-enable.yaml
tests/generated/controlplane.aws.yaml

ingress rule for support is missing

Fix ingress for support

---

charts/dataplane/templates/_helpers.tpl
tests/generated/dataplane.aws.with-ingress.yaml
tests/generated/dataplane.aws.yaml
tests/generated/dataplane.cost.yaml
tests/generated/dataplane.dcgm-exporter.yaml
tests/generated/dataplane.fully-selfhosted.yaml
tests/generated/dataplane.nodeobserver.yaml
tests/generated/dataplane.oci.yaml

Update the label to flyte-pod-webhook to be consistent with BYOC

update flytepropellerwebhook label
