README.md, charts/dataplane-crds/Chart.yaml, charts/dataplane/Chart.yaml, charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/common/cluster-secret.yaml, charts/dataplane/templates/operator/deployment-proxy.yaml, charts/dataplane/templates/operator/deployment.yaml, charts/dataplane/templates/operator/service-proxy.yaml, charts/dataplane/templates/operator/service.yaml, charts/dataplane/values.yaml
=> ctx/fix(dataplane): fix labels and names

charts/dataplane/Chart.yaml, charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/operator/monitoring.yaml, charts/dataplane/templates/propeller/deployment-webhook.yaml, charts/dataplane/templates/propeller/service-webhook.yaml, charts/dataplane/templates/propeller/service.yaml, charts/dataplane/values.yaml
Adds a service monitor for union services.
=> ctx/feat(monitoring): add service monitor for union services

charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/dcgm-exporter/daemonset.yaml, charts/dataplane/templates/dcgm-exporter/service.yaml, charts/dataplane/templates/dcgm-exporter/serviceaccount.yaml, charts/dataplane/values.yaml
=> ctx/chore(monitoring): clean annotations and values

charts/dataplane/templates/_storage.tpl, charts/dataplane/values.yaml, providers/oci/outputs.tf, providers/oci/storage.tf, providers/oci/variables.tf
=> ctx/fix(dataplane): fast registration config invalid

Makefile, charts/dataplane/Chart.yaml, charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/clusterresourcesync/deployment.yaml, charts/dataplane/templates/operator/deployment-proxy.yaml, charts/dataplane/templates/operator/deployment.yaml, charts/dataplane/templates/propeller/deployment-webhook.yaml, charts/dataplane/templates/propeller/deployment.yaml, charts/dataplane/values.yaml
=> ctx/feat(dataplane): add scheduling constraints

charts/dataplane/Chart.yaml, charts/dataplane/templates/clusterresourcesync/deployment.yaml, charts/dataplane/templates/operator/deployment-proxy.yaml, charts/dataplane/templates/operator/deployment.yaml, charts/dataplane/templates/propeller/deployment-webhook.yaml, charts/dataplane/templates/propeller/deployment.yaml, charts/dataplane/values.yaml
=> ctx/chore(dataplane): use chart appVersion

charts/dataplane/Chart.yaml, charts/dataplane/values.yaml
=> ctx/chore(dataplane): disable extra obs features by default

charts/dataplane/Chart.yaml, charts/dataplane/values.yaml
=> ctx/fix(dataplane): update default value to array

charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/clusterresourcesync/deployment.yaml, charts/dataplane/templates/clusterresourcesync/serviceaccount.yaml, charts/dataplane/templates/operator/serviceaccount.yaml, charts/dataplane/values.yaml
=> ctx/fix(clusterresourcesync): add rbac

charts/dataplane/Chart.yaml, charts/dataplane/templates/propeller/service-webhook.yaml
=> ctx/fix(webhook): ensure correct service name

charts/dataplane/templates/_helpers.tpl
=> ctx/chore(dataplane): add PROXY_SERVICE_URL to global pod env

charts/dataplane/templates/_helpers.tpl
=> ctx/chore(dataplane): add additional service URLs

charts/dataplane/Chart.yaml, charts/dataplane/values.yaml
=> ctx/fix(prom): rename prometheus components

charts/dataplane/templates/_helpers.tpl, charts/dataplane/values.yaml
=> ctx/fix(dataplane): prom svc to port 80

charts/dataplane-crds/Chart.yaml, charts/dataplane/Chart.yaml
When installing these charts on an AWS EKS cluster, we're currently failing with
```
Error: chart requires kubeVersion: >= 1.28.0 which is incompatible with Kubernetes v1.32.2-eks-bc803b4
```
Changing the constraint to `>= 1.28.0-0` allows us to support pre-release and vendor-specific versions.
Tested this locally, the fix works.
fixes D-1111
=> fix(helm): support vendor-specific versions of k8s

charts/dataplane/Chart.yaml, charts/dataplane/values.yaml
We depend on `metrics-server` for billable usage.  Because `metrics-server` creates an `APIService`, we can only run this component once per cluster.  This change assumes cluster administrators will likely already be running `metrics-server`, so we won't install it by default.
Should cluster administrators not want to worry about installing `metrics-server` themselves, they can set:
```
monitoring:
metricsServer:
enabled: true
```
And this chart will install it.
Tested this against `byok-aws`
fixes D-1124
=> chore(charts/dataplane): add dependency on k8s-sigs metrics-server chart

providers/aws/provider.tf, providers/aws/variables.tf
I had some trouble getting all of the default components (operator, operator-proxy, prometheus) to schedule on `m7i.xlarge`.  Changes the default to `m7i.2xlarge`.
Also uncomments the `token` field for the Helm provider.
=> fix(terraform-aws): use larger default instance type, helm token

charts/dataplane-crds/templates/flyteworkflow.yaml, charts/dataplane/templates/_helpers.tpl
I'm working on deploying the dataplane chart with ArgoCD.  The `resourceFieldRef.divisor` field isn't specified in our chart, and after applying the generated manifests the server-side state shows `divisor: '0'`.  This is a bit odd, but possibly seems related to https://github.com/kubernetes/kubernetes/issues/128865
This change sets `divisor: 1` which is the default value in Kubernetes.
=> fix(dataplane-chart): Specify resourceFieldRef.divisor

Makefile, README.md, charts/dataplane/README.md, charts/dataplane/templates/_storage.tpl, charts/dataplane/templates/clusterresourcesync/deployment.yaml, charts/dataplane/templates/common/auth-secret.yaml, charts/dataplane/templates/propeller/deployment.yaml, charts/dataplane/values.yaml, providers/aws/iam.tf
I've been iterating on standing up a cluster in AWS and ran into some issues, details below.
- I wanted to manage the client secret manually, think via something like ExternalSecrets or HashiCorp Vault.  This meant I didn't want to pass the secret via Helm values
- Currently the chart creates the secret if `secrets.admin.enabled` is set
- It also assumes that if `secrets.admin.enabled=false`, it does not need to wire up the volume mounts.  This feels incorrect to me, we should wire them up regardless and only use `secrets.admin.enabled` to manage creation of the secret.  If that's the case, `secrets.admin.create` is probably the better variable to use here -- which lines up with the example in the README
- 👉 **tl;dr** - Refactored to `secrets.admin.create` to guard secret creation, always …
=> fix(dataplane): Misc fixes related to secrets and AWS IAM roles

providers/aws/iam.tf, providers/aws/locals.tf
Adds `union-health-monitoring` to the permitted projects for IAM role use.
=> fix(terraform-aws): fix union-health-monitoring permissions

.github/workflows/release.yaml, charts/dataplane/Chart.yaml, charts/dataplane/templates/_storage.tpl
=> ctx/fix(dataplane): remove newline trim when using fastRegistrationURL

charts/dataplane/templates/operator/configmap.yaml, charts/dataplane/templates/serving/knative-serving.yaml, tests/generated/dataplane.oci.yaml
Missed both of these in my previous changes:
- Does not use the `cloudHostName` helper which was an internal implementation detail
- Adds missing operator config
=> fix(serving): Do not use cloudHostName helper, add operator config

charts/dataplane/templates/operator/configmap.yaml, charts/dataplane/templates/operator/serviceaccount.yaml, charts/dataplane/values.yaml, tests/generated/dataplane.oci.yaml
- Adds RBAC permissions to interact with KnativeServing resources when serving is enabled
- Prefers to use top-level `serving.enabled` flag for a better UX
=> fix(serving): add permissions for serving, fix configuration

charts/dataplane/templates/operator/configmap.yaml, charts/dataplane/values.yaml, tests/generated/dataplane.aws.yaml, tests/generated/dataplane.oci.yaml
=> ctx/fix(dataplane): disable identity caching

charts/dataplane/values.yaml, tests/generated/dataplane.aws.yaml, tests/generated/dataplane.oci.yaml
This config sets the maximum file size allowed for download. The example in https://linear.app/unionai/issue/D-1184/troubleshoot-and-fix-data-offloading-in-byok failed with hitting the limit. Typically we set this to 1024.
=> bump max download limit

charts/dataplane/values.yaml, tests/generated/dataplane.aws.yaml, tests/generated/dataplane.dcgm-exporter.yaml, tests/generated/dataplane.oci.yaml
=> ctx/fix(dataplane): allow prom to select anywhere

charts/dataplane/values.yaml, tests/generated/dataplane.aws.yaml, tests/generated/dataplane.dcgm-exporter.yaml, tests/generated/dataplane.oci.yaml
=> ctx/chore(dataplane): set default prom retention to 3 days

charts/dataplane/Chart.yaml, charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/imagebuilder/configmap.yaml, charts/dataplane/templates/imagebuilder/deployment.yaml, charts/dataplane/templates/imagebuilder/hpa.yaml, charts/dataplane/templates/imagebuilder/pdb.yaml, charts/dataplane/templates/imagebuilder/service.yaml, charts/dataplane/templates/operator/configmap.yaml, charts/dataplane/templates/operator/serviceaccount.yaml, charts/dataplane/values.yaml, tests/generated/dataplane.aws.yaml, tests/generated/dataplane.dcgm-exporter.yaml, tests/generated/dataplane.nodeobserver.yaml, tests/generated/dataplane.oci.yaml
Update the dataplane helm chart to support Image Builder.
Notable changes:
* Update values.yaml with appropriate configuration.
* Conditionally provision buildkit deployment.
* Update operator service account with additional permissions for
namespaces and secrets.
Depends on https://github.com/unionai/cloud/pull/11588
=> Image Builder support.

charts/controlplane/.helmignore, charts/controlplane/Chart.yaml, charts/controlplane/templates/NOTES.txt, charts/controlplane/templates/_helpers.tpl, charts/controlplane/templates/configmap.yaml, charts/controlplane/templates/deployment.yaml, charts/controlplane/templates/hpa.yaml, charts/controlplane/templates/pdb.yaml, charts/controlplane/templates/probe.yaml, charts/controlplane/templates/secret.yaml, charts/controlplane/templates/service.yaml, charts/controlplane/templates/serviceaccount.yaml, charts/controlplane/values.yaml, tests/generated/controlplane.aws.yaml, tests/values/controlplane.aws.yaml
* Adds green field templates working of the existing one in union cloud
* The templates are refactored to be able to install multiple services with single values file
* Adds helper to do recursive merges of the values
* Add override for controlplane chart to be installed with flag enabled for it
* Adds  generated tests
Tested this on internal EKS cluster and all services come up
=> Union services control plane charts

charts/dataplane/Chart.yaml, charts/dataplane/templates/imagebuilder/deployment.yaml, charts/dataplane/values.yaml
* Bump dataplane version from `2025.5.2` -> `2025.5.3`
* Fix image builder buildkit deployment helm template to remove breaking
condition when not using rootless
* Default to `non-rootless` buildkit to support a wider varient of out
of the box kernels. For example EKS AutoMode using bottlerocket which
limits user namespaces and breaks buildkit deployment
* add ephemeral-storage
=> Fix image builder helm-charts

charts/dataplane/templates/_helpers.tpl, tests/generated/dataplane.aws.yaml, tests/generated/dataplane.dcgm-exporter.yaml, tests/generated/dataplane.nodeobserver.yaml, tests/generated/dataplane.oci.yaml
In BYOC we use `app.kubernetes.io/name: union-operator`. This PR fix the inconsistency.
=> Make operator label same as the one in BYOC

.github/workflows/checks.yaml, charts/dataplane/Chart.yaml, charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/common/ingress.yaml, charts/dataplane/values.yaml, tests/generated/dataplane.aws.yaml, tests/generated/dataplane.cost.yaml, tests/generated/dataplane.dcgm-exporter.yaml, tests/generated/dataplane.nodeobserver.yaml, tests/generated/dataplane.oci.yaml
* Create Data plane ingress singular rule for App serving.
* Unrelated. Update kube-prometheus-stack to latest pinned version
because there was a templating error in our previous build. This
templating error caused `make generate-expected` to fail.
=> Data plane ingress

charts/dataplane/templates/_helpers.tpl, charts/dataplane/templates/common/extra-manifests.yaml, charts/dataplane/templates/serving/knative-serving.yaml, charts/dataplane/values.yaml
* Make app-serving Union authn and authz enablement configurable
* Add support for adding arbitrary manifests via `extraObjects` pattern.
E.g. supports ability to add alb ingress classes but can be extended
to anything including Union future CRDs.
=> Configurable app-serving auth and extra manifests

charts/controlplane/values.yaml, tests/generated/controlplane.aws.yaml
Workspaces rely on notification queues and currently we dont have  an offering for queues for onprem and hence we will need to disable this feature
Added config to disable it.
=> Disable workspaces in selfhosted

charts/controlplane/Chart.yaml, charts/controlplane/templates/_helpers.tpl, charts/controlplane/templates/deployment.yaml, charts/controlplane/templates/extra-manifests.yaml, charts/controlplane/values.yaml, charts/dataplane/Chart.yaml, charts/dataplane/values.yaml, tests/run.sh
* Adds ingrss-nginx controller to `controlplane` and `dataplane`,
default to disabled.
* Adding to both to allow users to run dataplane or controlplane in
isolation.
* Add `extraObjects` in controlplane to allow users to deploy extra
Kubernetes manifests.
* Add support for overriding secrets in controlplane
=> ingress-nginx, extraObjects, add override service secrets in controlplane

charts/controlplane/templates/common/_ingress-protected-console.yaml, charts/controlplane/templates/flyte-core-app.yaml, charts/controlplane/values.yaml, tests/generated/controlplane.aws.billing-enable.yaml, tests/generated/controlplane.aws.yaml, tests/run.sh
The UI is up here https://selfhosted.cloud-staging.union.ai/console/projects/union-health-monitoring/domains/development/dashboard
Though slower on initial load due to dependency on unleash we wont have in constrained environment
=> [D-1247] Enable flyteconsole in selfhosted

charts/controlplane/templates/common/_dataproxy-ingress.yaml, charts/controlplane/templates/common/_ingress-protected.yaml, charts/controlplane/templates/common/_ingress-unprotected.yaml, charts/controlplane/templates/common/_usage-ingress.yaml, charts/controlplane/values.yaml, charts/dataplane/templates/common/ingress.yaml, tests/generated/controlplane.aws.billing-enable.yaml, tests/generated/controlplane.aws.yaml, tests/generated/dataplane.aws.with-ingress.yaml
* Include explicit ingress class only when nonempty string
* Remove default nginx ingress class annotation
=> Fix ingress class inclusion and remove default ingress class annotation

charts/controlplane/templates/_helpers.tpl, charts/controlplane/templates/cacheservice/configmap.yaml, charts/controlplane/templates/cacheservice/deployment.yaml, charts/controlplane/templates/cacheservice/rbac.yaml, charts/controlplane/templates/cacheservice/service.yaml, charts/controlplane/values.yaml, tests/generated/controlplane.aws.billing-enable.yaml, tests/generated/controlplane.aws.yaml
Registered flytesnacks lifecycle examples which demonstrate caching
https://github.com/flyteorg/flytesnacks/releases/tag/v0.3.341
Verified the cache was written 
https://selfhosted.cloud-staging.union.ai/console/projects/union-health-monitoring/domains/development/executions/a4flvt2fjblrzgcnr4h4/nodes
Verified this was all read from the cache
https://selfhosted.cloud-staging.union.ai/console/projects/union-health-monitoring/domains/development/executions/a25cmtvp79ldbqbnhbrn/nodes
=> Add cache service for the controlplane
